import type {
	TerminalCommandListBlock,
	TerminalCommandOutput,
	TerminalJsonBlock,
	TerminalTextBlock,
} from "@/features/terminal/types";

/** Maps semantic text tones to the Tailwind classes used by the terminal output. */
function getToneClassName(tone: TerminalTextBlock["tone"] = "default") {
	if (tone === "error") return "text-red-500";
	if (tone === "success") return "text-lime-500";
	if (tone === "muted") return "text-gray-300";
	return "text-white";
}

/**
 * Renders a plain text output block.
 *
 * @param block Terminal output block containing textual content.
 * @param index Stable fallback index used to build the React key.
 * @returns Paragraph element styled according to the block tone and weight.
 */
function renderTextBlock(block: TerminalTextBlock, index: number) {
	const className =
		`${getToneClassName(block.tone)} ${block.weight === "bold" ? "font-bold" : ""}`.trim();
	return (
		<p className={className} key={`text-${index}`}>
			{block.text}
		</p>
	);
}

/**
 * Renders a JSON output block using preformatted text.
 *
 * @param block Terminal output block containing serializable data.
 * @param index Stable fallback index used to build the React key.
 * @returns Preformatted element with a serialized JSON payload.
 */
function renderJsonBlock(block: TerminalJsonBlock, index: number) {
	return (
		<pre className="whitespace-pre-wrap" key={`json-${index}`}>
			{JSON.stringify(block.data, null, 2)}
		</pre>
	);
}

/**
 * Renders the command list used by the help response.
 *
 * @param block Terminal output block containing command summaries.
 * @param index Stable fallback index used to build the React key.
 * @returns Definition-style list of available terminal commands.
 */
function renderCommandListBlock(block: TerminalCommandListBlock, index: number) {
	return (
		<div className="space-y-2" key={`commands-${index}`}>
			<dl>
				{block.commands.map((command) => (
					<div key={command.name} className="mb-2">
						<span className="font-semibold">
							{command.name} {command.params ?? null}
						</span>
						<span className="ml-2! text-sm text-gray-300">{command.description}</span>
					</div>
				))}
			</dl>
		</div>
	);
}

interface TerminalOutputRendererProps {
	/** Structured command output to display. */
	output: TerminalCommandOutput;
}

/**
 * Renders the blocks returned by a terminal command in their corresponding UI format.
 *
 * @param output Structured output generated by a terminal command executor.
 * @returns Fragment containing the rendered terminal blocks.
 */
export function TerminalOutputRenderer({ output }: TerminalOutputRendererProps) {
	return (
		<>
			{output.blocks.map((block, index) => {
				if (block.type === "text") return renderTextBlock(block, index);
				if (block.type === "json") return renderJsonBlock(block, index);
				return renderCommandListBlock(block, index);
			})}
		</>
	);
}
