/** Shared types used by the interactive terminal feature. */
export interface TerminalOutputEntry {
	/** Stable identifier used to render output entries in React lists. */
	id: string;
	/** Structured payload generated by a command execution. */
	content: TerminalCommandOutput;
}

export interface TerminalCommandContext {
	/** Clears the rendered terminal output. */
	clearOutput?: () => void;
	/** Updates the visual blur level used by the terminal background. */
	setBlur?: (value: number) => void;
	/** Switches the terminal display mode between supported variants. */
	setDisplayMode?: (mode: string) => void;
	/** Selects the active panorama image shown behind the terminal. */
	setPanorama?: (panorama: number) => void;
}

/** Visual tone applied to text blocks rendered in the terminal output. */
export type TerminalTextTone = "default" | "error" | "success" | "muted";

export interface TerminalTextBlock {
	/** Discriminator used by the renderer to identify text output. */
	type: "text";
	/** Plain text content shown in the terminal. */
	text: string;
	/** Optional semantic color preset for the message. */
	tone?: TerminalTextTone;
	/** Optional font weight used for emphasis. */
	weight?: "normal" | "bold";
}

export interface TerminalJsonBlock {
	/** Discriminator used by the renderer to identify JSON output. */
	type: "json";
	/** Optional title displayed before the JSON payload. */
	title?: string;
	/** Arbitrary serializable data returned by a command. */
	data: unknown;
}

export interface TerminalCommandSummary {
	/** Terminal command name including its slash prefix. */
	name: string;
	/** Optional parameter signature shown in the help listing. */
	params?: string;
	/** Human-readable explanation of the command behavior. */
	description: string;
}

export interface TerminalCommandListBlock {
	/** Discriminator used by the renderer to identify command listings. */
	type: "command-list";
	/** Set of command summaries rendered in the help output. */
	commands: TerminalCommandSummary[];
}

/** Union of all output block shapes supported by the terminal renderer. */
export type TerminalOutputBlock = TerminalTextBlock | TerminalJsonBlock | TerminalCommandListBlock;

export interface TerminalCommandOutput {
	/** Ordered blocks that compose the rendered command response. */
	blocks: TerminalOutputBlock[];
}

/** Result type returned by command executors, supporting sync and async flows. */
export type TerminalCommandResult =
	| TerminalCommandOutput
	| null
	| Promise<TerminalCommandOutput | null>;

/** Function signature implemented by every terminal command executor. */
export type TerminalCommandExecutor = (
	args: string[],
	context: TerminalCommandContext,
) => TerminalCommandResult;

export interface TerminalCommandDefinition {
	/** Public command name used in the terminal input. */
	name: string;
	/** Optional parameter signature shown in help and listings. */
	params?: string;
	/** Short explanation of what the command does. */
	description: string;
	/** Function invoked when the command is executed. */
	execute: TerminalCommandExecutor;
}
